/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.leadingcompass;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.cloud.netflix.zuul.EnableZuulProxy;
import org.springframework.context.annotation.Bean;

import com.leadingcompass.filters.PreSimpleFilter;

@EnableZuulProxy //Zuul Proxy Server
@EnableDiscoveryClient //Eureka Client
@SpringBootApplication
public class App {
    public String getGreeting() {
        return "Hello world.";
    }
    @Bean
    public PreSimpleFilter simpleFilter() {
        return new PreSimpleFilter();
    }
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}